# File: .github/workflows/deploy.yml
name: Deploy WordPress Plugin

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'auto-alt-text-for-images.php'
      - 'readme.txt'

jobs:
  build-and-deploy:
    name: Build and Deploy Plugin
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '✨ Release version')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, wp-cli

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from commit message
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '✨ Release version \K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci

      - name: Generate POT file
        run: |
          mkdir -p languages
          wp i18n make-pot . languages/auto-alt-text-for-images.pot --domain=auto-alt-text-for-images --allow-root

      - name: Create ZIP archive
        run: composer run zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/auto-alt-text-for-images.zip
          body_path: CHANGELOG.md
          name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout WordPress SVN repository
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          svn checkout "https://plugins.svn.wordpress.org/auto-alt-text-for-images" \
          --username "$SVN_USERNAME" \
          --password "$SVN_PASSWORD" \
          --no-auth-cache \
          --non-interactive \
          --trust-server-cert \
          svn

      - name: Prepare SVN
        working-directory: svn
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          # Clean directories
          rm -rf trunk/* tags/$VERSION
          rm -rf assets/*
          
          # Create necessary directories
          mkdir -p assets
          mkdir -p trunk/assets
          mkdir -p tags/$VERSION/assets
          
          # Copy images to SVN assets directory (only images)
          cp -r ../assets/*.{jpg,jpeg,png,gif,svg,webp} assets/ 2>/dev/null || true
          svn add assets/* --force
          
          # Copy CSS and JS to trunk/assets
          mkdir -p trunk/assets/css trunk/assets/js
          cp -r ../assets/css/* trunk/assets/css/ 2>/dev/null || true
          cp -r ../assets/js/* trunk/assets/js/ 2>/dev/null || true
          
          # Copy other plugin files to trunk
          cp -r ../includes trunk/
          cp -r ../languages trunk/
          cp -r ../templates trunk/
          cp ../auto-alt-text-for-images.php trunk/
          cp ../README.md trunk/
          cp ../readme.txt trunk/
          cp ../uninstall.php trunk/
          
          # Add all trunk files to SVN
          svn add trunk/* --force
          
          # Create and populate version tag
          cp -r trunk/* tags/$VERSION/
          svn add tags/$VERSION --force
          
          # Remove any deleted files
          svn status | grep '^\!' | sed 's/! *//' | xargs -I% svn rm %@

      - name: Commit to SVN
        working-directory: svn
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          svn commit -m "Release version $VERSION" \
            --username "$SVN_USERNAME" \
            --password "$SVN_PASSWORD" \
            --no-auth-cache \
            --non-interactive \
            --trust-server-cert

      - name: Notify on success
        if: success()
        run: |
          echo "Plugin successfully deployed to WordPress.org and GitHub!"
          echo "Version ${{ steps.get_version.outputs.version }} is now live!"