name: Deploy WordPress Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    name: Build and Deploy Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, wp-cli

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci

      - name: Generate POT file
        run: |
          mkdir -p languages
          wp i18n make-pot . languages/auto-alt-text-for-images.pot --domain=auto-alt-text-for-images --allow-root

      - name: Create ZIP archive
        run: composer run zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/auto-alt-text-for-images.zip
          body_path: CHANGELOG.md
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout WordPress SVN repository
        run: |
          svn checkout https://plugins.svn.wordpress.org/auto-alt-text-for-images svn --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}

      - name: Prepare SVN
        working-directory: svn
        run: |
          VERSION=${{ github.ref_name }}
          rm -rf trunk/* tags/$VERSION
          rm -rf assets/*
          cp -r ../assets/* assets/
          svn add assets/* --force
          cp -r ../includes trunk/
          cp -r ../languages trunk/
          cp -r ../templates trunk/
          cp ../auto-alt-text-for-images.php trunk/
          cp ../README.md trunk/
          cp ../readme.txt trunk/
          cp ../uninstall.php trunk/
          svn add trunk/* --force
          mkdir -p tags/$VERSION
          cp -r trunk/* tags/$VERSION/
          svn add tags/$VERSION --force
          svn status | grep '^\!' | sed 's/! *//' | xargs -I% svn rm %@

      - name: Commit to SVN
        working-directory: svn
        run: |
          VERSION=${{ github.ref_name }}
          svn commit -m "Release version $VERSION" \
            --username ${{ secrets.SVN_USERNAME }} \
            --password ${{ secrets.SVN_PASSWORD }}

      - name: Notify on success
        if: success()
        run: |
          echo "Plugin successfully deployed to WordPress.org and GitHub!"
          echo "Version ${{ github.ref_name }} is now live!"